create table table_1 (user_id INT, name VARCHAR(50),age INT, salary INT, PRIMARY KEY (user_id));
insert into table_1 values (1, 'John', 23, 400);
insert into table_1 values (2, 'Mary', 20,450);
insert into table_1 values (3, 'Max', 29,1200);
insert into table_1 values (4, 'Felix', 218,350);
insert into table_1 values (5, 'Groover', 22,570);
insert into table_1 values (6, 'Ben', 19,620);
select name from table_1 where user_id = 6;
select name from table_1 where salary>=500;
insert into table_1 values (7,'Denis',23,600);
delete from table_1 where user_id=7;
select name from table_1 where salary>=500 and salary<=1000;
create table table_2 (user_id int, phone_number int, years_of_experience int, primary key (user_id));
insert into table_2 values(1,433443,2);
insert into table_2 values(2,111111,1);
insert into table_2 values(3,123456,7);
insert into table_2 values(4,123568,0);
insert into table_2 values(5,191919,1);
insert into table_2 values(6,121212,1);
UPDATE table_2 SET years_of_experience=9 WHERE EXISTS (select name from table_1 where (name='Max') and (table_1.user_id = table_2.user_id) ) ;
select years_of_experience from table_2 where user_id =3;
select name from table_1 where (age>=23 and age<27) or (salary = 1000);
select * from table_1 where (name = 'John') or (name  = 'Mary');
select phone_number from table_2 where exists (select name from table_1 where (name= 'John') and (table_1.user_id = table_2.user_id));
select name from table_1 where exists (select phone_number from table_2 where (table_1.user_id = table_2.user_id) and (phone_number/100000 = 1));
select name from table_1 where exists (select years_of_experience from table_2 where (table_1.user_id = table_2.user_id) and (years_of_experience>2));
